name: 编译并推送docker镜像

on:
  push:
    branches: [main]
  pull_request:

env:
  OTP-VERSION: 26.2.2
  REBAR3-VERSION: 3.22.1

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: erlef/setup-beam@v1.17.5
        with:
          otp-version: ${{ env.OTP-VERSION }}
          rebar3-version: ${{ env.REBAR3-VERSION }}

      - uses: actions/cache@v4.0.2
        id: rebar3-cache
        with:
          path: |
            ~/.cache/rebar3
            _build
          key: ${{ runner.os }}-${{ env.OTP-VERSION }}-${{ env.REBAR3-VERSION }}-${{ hashFiles('rebar.lock') }}

      - name: Compile
        run: |
          rebar3 clean
          rebar3 compile

      - run: rebar3 check

      - run: rebar3 test

      - uses: test-summary/action@vv2.3
        if: always()
        with:
          paths: '_build/test/logs/**/report.xml'

      # 设置Docker构建环境
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.3.0

      # 登录Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 构建Docker镜像
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: redgreat/eadm:latest
