version: '3.8'
services:
    postgres:
        image: 'redgreat/postgres:latest'
        container_name: postgres
        hostname: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: user_eadm
            POSTGRES_DB: eadm
            POSTGRES_PASSWORD: iyS62bvt
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    eadm:
      image: 'redgreat/eadm:latest'
      container_name: eadm
      restart: unless-stopped
      ports:
        - '8080:8090'
      volumes:
        - ./config/prod_db.config:/opt/eadm/releases/0.1.14/prod_db.config
        - ./config/sys.config.src:/opt/eadm/releases/0.1.14/sys.config.src
        - ./config/vm.args.src:/opt/eadm/releases/0.1.14/vm.args.src
        - ./log/:/var/log/eadm/
      environment:
        DISABLE_IPV6: 'true'
      depends_on:
          - postgres
      deploy:
        resources:
          limits:
            memory: 1G
          reservations:
            memory: 500M
      mem_swappiness: 0
      oom_kill_disable: true
