-- @AUTHOR WANGCW
-- @COPYRIGHT (C) 2024, REDGREAT
-- CREATED : 2024-06-14 13:43:30
-- ORACLE表结构设计

-- SELECT * FROM V$VERSION;
ALTER SESSION SET TIME_ZONE='ASIA/SHANGHAI';
--'ASIA/SHANGHAI' OR '+08:00';
-- SELECT DBTIMEZONE FROM DUAL;
-- SELECT SESSIONTIMEZONE FROM DUAL;

-- 创建序列
-- DROP SEQUENCE SEQ_SD;
CREATE SEQUENCE SEQ_SD
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- SELECT SEQ_SD.NEXTVAL FROM DUAL;

-- 系统_字典信息表
DROP TABLE SYS_DICT;
CREATE TABLE SYS_DICT (
  ID CHAR(12) NOT NULL,
  DICTNO VARCHAR2(50) NOT NULL,
  DICTNAME VARCHAR2(100) NOT NULL,
  PARENTID CHAR(12),
  CREATEDUSER VARCHAR2(50),
  CREATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  UPDATEDUSER VARCHAR2(50),
  UPDATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  DELETEDUSER VARCHAR2(50),
  DELETEDAT TIMESTAMP WITH LOCAL TIME ZONE,
  DELETED INTEGER DEFAULT 0
);

ALTER TABLE SYS_DICT ADD CONSTRAINT PK_SYSDICT_ID PRIMARY KEY (ID);
ALTER TABLE SYS_DICT ADD CONSTRAINT UNI_SYSDICT_DICTNO UNIQUE (DICTNO);
ALTER TABLE SYS_DICT ADD CONSTRAINT CK_SYSDICT_DELETED CHECK (DELETED IN (0, 1));
ALTER TABLE SYS_DICT ADD CONSTRAINT FK_PARENTID_SYSDICT_ID FOREIGN KEY (PARENTID)
    REFERENCES SYS_DICT (ID);
CREATE INDEX NON_SYSDICT_PARENTID ON SYS_DICT (PARENTID ASC);

COMMENT ON COLUMN SYS_DICT.ID IS '自定义主键(SD)';
COMMENT ON COLUMN SYS_DICT.DICTNO IS '字典编码';
COMMENT ON COLUMN SYS_DICT.DICTNAME IS '字典名称';
COMMENT ON COLUMN SYS_DICT.PARENTID IS '父级ID';
COMMENT ON COLUMN SYS_DICT.CREATEDUSER IS '创建人';
COMMENT ON COLUMN SYS_DICT.CREATEDAT IS '创建时间';
COMMENT ON COLUMN SYS_DICT.UPDATEDUSER IS '更新人';
COMMENT ON COLUMN SYS_DICT.UPDATEDAT IS '更新时间';
COMMENT ON COLUMN SYS_DICT.DELETEDUSER IS '删除人';
COMMENT ON COLUMN SYS_DICT.DELETEDAT IS '删除时间';
COMMENT ON COLUMN SYS_DICT.DELETED IS '是否删除(0否1是)';
COMMENT ON TABLE SYS_DICT IS '系统_字典信息表';

-- 更新时间
CREATE OR REPLACE TRIGGER TR_SYS_DICT_UPDATEAT
BEFORE UPDATE ON SYS_DICT
FOR EACH ROW
BEGIN
    :NEW.UPDATEDAT := SYSTIMESTAMP;
END;

--自定义主键
CREATE OR REPLACE TRIGGER TR_SYS_DICT_ID
BEFORE INSERT ON SYS_DICT
FOR EACH ROW
BEGIN
    :NEW.ID := 'SD' || LPAD(SEQ_SD.NEXTVAL, 10, '0');
END;

-- 测试数据写入
-- TRUNCATE TABLE SYS_DICT;
-- INSERT INTO SYS_DICT(DICTNO, DICTNAME, PARENTID, CREATEDUSER, UPDATEDUSER)
-- VALUES('TEST', '测试字典', NULL, 'WANGCW','WANGCW');
-- INSERT INTO SYS_DICT(DICTNO, DICTNAME, PARENTID, CREATEDUSER, UPDATEDUSER)
-- VALUES('TESTSUB', '测试字典子选项', 'SD0000000001', 'WANGCW','WANGCW');
-- UPDATE SYS_DICT SET DICTNO='TEST1' WHERE ID='SD0000000001';
-- SELECT * FROM SYS_DICT;

-- 基础信息_租户信息表
CREATE SEQUENCE SEQ_ET
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE TABLE EADM_TENANT (
  ID CHAR(12) NOT NULL,
  TENANTNAME VARCHAR2(20) NOT NULL,
  REMARK VARCHAR2(100),
  ENABLE INTEGER DEFAULT 1,
  CREATEDUSER VARCHAR2(50),
  CREATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  UPDATEDUSER VARCHAR2(50),
  UPDATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  DELETEDUSER VARCHAR2(50),
  DELETEDAT TIMESTAMP WITH LOCAL TIME ZONE,
  DELETED INTEGER DEFAULT 0
);

ALTER TABLE EADM_TENANT ADD CONSTRAINT PK_TENANT_ID PRIMARY KEY (ID);
ALTER TABLE EADM_TENANT ADD CONSTRAINT UNI_TENANT_TENANTNAME UNIQUE (TENANTNAME);

CREATE INDEX NON_TENANT_ENABLE ON EADM_TENANT (ENABLE ASC);

COMMENT ON COLUMN EADM_TENANT.ID IS '自定义主键(ET)';
COMMENT ON COLUMN EADM_TENANT.TENANTNAME IS '租户名称';
COMMENT ON COLUMN EADM_TENANT.REMARK IS '备注信息';
COMMENT ON COLUMN EADM_TENANT.ENABLE IS '是否可用(0否1是)';
COMMENT ON COLUMN EADM_TENANT.CREATEDUSER IS '创建人';
COMMENT ON COLUMN EADM_TENANT.CREATEDAT IS '创建时间';
COMMENT ON COLUMN EADM_TENANT.UPDATEDUSER IS '更新人';
COMMENT ON COLUMN EADM_TENANT.UPDATEDAT IS '更新时间';
COMMENT ON COLUMN EADM_TENANT.DELETEDUSER IS '删除人';
COMMENT ON COLUMN EADM_TENANT.DELETEDAT IS '删除时间';
COMMENT ON COLUMN EADM_TENANT.DELETED IS '是否删除(0否1是)';
COMMENT ON TABLE EADM_TENANT IS '基础信息_租户信息表';

-- 更新时间
CREATE OR REPLACE TRIGGER TR_EADM_TENANT_UPDATEAT
BEFORE UPDATE ON EADM_TENANT
FOR EACH ROW
BEGIN
    :NEW.UPDATEDAT := SYSTIMESTAMP;
END;

--自定义主键
CREATE OR REPLACE TRIGGER TR_EADM_TENANT_ID
BEFORE INSERT ON EADM_TENANT
FOR EACH ROW
BEGIN
    :NEW.ID := 'ET' || LPAD(SEQ_ET.NEXTVAL, 10, '0');
END;

--写入数据
TRUNCATE TABLE EADM_TENANT;

INSERT INTO EADM_TENANT(TENANTNAME, REMARK, CREATEDUSER)
VALUES('REDGREAT', '主租户', 'WANGCW');

INSERT INTO EADM_TENANT(TENANTNAME, REMARK, CREATEDUSER)
VALUES('管理客户', '手动添加客户', 'WANGCW');

INSERT INTO EADM_TENANT(TENANTNAME, REMARK, CREATEDUSER)
VALUES('注册客户', '界面注册客户', 'WANGCW');

-- SELECT * FROM EADM_TENANT;

-- 获取商户名称
CREATE OR REPLACE FUNCTION EADM.FN_GETTENANTNAME(INID IN CHAR)
RETURN VARCHAR2
IS
  V_TENANT_NAME VARCHAR2(100);
BEGIN
  SELECT TENANTNAME
    INTO V_TENANT_NAME
  FROM EADM_TENANT
  WHERE ID = INID
    AND ENABLE = 1
    AND DELETED = 0
    AND ROWNUM = 1;

--  IF SQL%NOTFOUND THEN
--    RAISE_APPLICATION_ERROR(-20001, 'NO TENANT FOUND WITH PROVIDED ID');
--  ELSIF SQL%ROWCOUNT > 1 THEN
--    RAISE_APPLICATION_ERROR(-20002, 'MORE THAN ONE TENANT FOUND WITH PROVIDED ID');
--  END IF;

  RETURN V_TENANT_NAME;
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END;

-- SELECT FN_GETTENANTNAME('ET0000000001') FROM DUAL;

-- 用户表
-- 创建序列
CREATE SEQUENCE SEQ_EU
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE TABLE EADM_USER (
  ID CHAR(12) NOT NULL,
  TENANTID CHAR(12) NOT NULL,
  LOGINNAME VARCHAR2(50) NOT NULL,
  USERNAME VARCHAR2(50) NOT NULL,
  EMAIL VARCHAR2(20),
  PASSWD VARCHAR2(50) NOT NULL,
  USERSTATUS SMALLINT DEFAULT 0,
  CREATEDUSER VARCHAR2(50),
  CREATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  UPDATEDUSER VARCHAR2(50),
  UPDATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  DELETEDUSER VARCHAR2(50),
  DELETEDAT TIMESTAMP WITH LOCAL TIME ZONE,
  DELETED INTEGER DEFAULT 0
);

ALTER TABLE EADM_USER ADD CONSTRAINT PK_USER_ID PRIMARY KEY (ID);

ALTER TABLE EADM_USER ADD CONSTRAINT FK_TENANTID_TENANT_ID FOREIGN KEY (TENANTID)
    REFERENCES EADM_TENANT (ID);

ALTER TABLE EADM_USER ADD CONSTRAINT UNI_USER_LOGINNAME UNIQUE (LOGINNAME);

CREATE INDEX NON_USER_USERSTATUS ON EADM_USER (USERSTATUS ASC);
CREATE INDEX NON_USER_UPDATEDAT ON EADM_USER (UPDATEDAT DESC);

COMMENT ON COLUMN EADM_USER.ID IS '自定义主键(EU)';
COMMENT ON COLUMN EADM_USER.TENANTID IS '租户ID';
COMMENT ON COLUMN EADM_USER.LOGINNAME IS '用户登录名';
COMMENT ON COLUMN EADM_USER.USERNAME IS '用户姓名';
COMMENT ON COLUMN EADM_USER.EMAIL IS '用户邮件';
COMMENT ON COLUMN EADM_USER.PASSWD IS '密码';
COMMENT ON COLUMN EADM_USER.USERSTATUS IS '用户状态(0启用1禁用)';
COMMENT ON COLUMN EADM_USER.CREATEDUSER IS '创建人';
COMMENT ON COLUMN EADM_USER.CREATEDAT IS '创建时间';
COMMENT ON COLUMN EADM_USER.UPDATEDUSER IS '更新人';
COMMENT ON COLUMN EADM_USER.UPDATEDAT IS '更新时间';
COMMENT ON COLUMN EADM_USER.DELETEDUSER IS '删除人';
COMMENT ON COLUMN EADM_USER.DELETEDAT IS '删除时间';
COMMENT ON COLUMN EADM_USER.DELETED IS '是否删除(0否1是)';
COMMENT ON TABLE EADM_USER IS '基础信息_用户信息表';

-- 更新时间
CREATE OR REPLACE TRIGGER TR_EADM_USER_UPDATEAT
BEFORE UPDATE ON EADM_USER
FOR EACH ROW
BEGIN
    :NEW.UPDATEDAT := SYSTIMESTAMP;
END;

--自定义主键
CREATE OR REPLACE TRIGGER TR_EADM_USER_ID
BEFORE INSERT ON EADM_USER
FOR EACH ROW
BEGIN
    :NEW.ID := 'EU' || LPAD(SEQ_EU.NEXTVAL, 10, '0');
END;

-- 写入用户数据

TRUNCATE TABLE EADM_USER;

-- SELECT * FROM EADM_TENANT;
-- SELECT * FROM EADM_USER;

INSERT INTO EADM_USER(TENANTID, LOGINNAME, USERNAME, EMAIL, PASSWD, CREATEDUSER)
VALUES('ET0000000001','WANGCW', '王存伟', 'RUBYGREAT@MSN.COM', 'Q122/4GBPICNQ83ABPQN/+KYQ0KWCZLXIWFLALKK4NY=', 'WANGCW');

INSERT INTO EADM_USER(TENANTID, LOGINNAME, USERNAME, EMAIL, PASSWD, CREATEDUSER)
VALUES('ET0000000001','WONGCW', '王存偉', 'RUBYGREAT@MSN.COM', 'Q122/4GBPICNQ83ABPQN/+KYQ0KWCZLXIWFLALKK4NY=', 'WANGCW');

INSERT INTO EADM_USER(TENANTID, LOGINNAME, USERNAME, EMAIL, PASSWD, CREATEDUSER)
VALUES('ET0000000001','JIANGYF', '姜玉凤', '1234567@QQ.COM', 'Q122/4GBPICNQ83ABPQN/+KYQ0KWCZLXIWFLALKK4NY=', 'WANGCW');

-- 用户视图
CREATE OR REPLACE VIEW VI_USER
AS
SELECT ID, FN_GETTENANTNAME(TENANTID) AS TENANTNAME, LOGINNAME, USERNAME, EMAIL,
       CASE USERSTATUS WHEN 1 THEN '禁用' WHEN 0 THEN '启用' END AS USERSTATUS, CREATEDAT
FROM EADM_USER
  WHERE DELETED = 0;

-- SELECT * FROM VI_USER;

-- 用户角色
-- 创建序列
CREATE SEQUENCE SEQ_ER
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE TABLE EADM_ROLE (
  ID CHAR(12) NOT NULL,
  ROLENAME VARCHAR2(50) NOT NULL,
  ROLEPERMISSION CLOB,
  ROLESTATUS SMALLINT DEFAULT 0,
  CREATEDUSER VARCHAR2(50),
  CREATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  UPDATEDUSER VARCHAR2(50),
  UPDATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  DELETEDUSER VARCHAR2(50),
  DELETEDAT TIMESTAMP WITH LOCAL TIME ZONE,
  DELETED INTEGER DEFAULT 0
);

ALTER TABLE EADM_ROLE ADD CONSTRAINT PK_ROLE_ID PRIMARY KEY (ID);

CREATE INDEX NON_ROLE_ROLENAME ON EADM_ROLE (ROLENAME ASC);
CREATE INDEX NON_USER_ROLESTATUS ON EADM_ROLE (ROLESTATUS ASC);

COMMENT ON COLUMN EADM_ROLE.ID IS '自定义主键(ER)';
COMMENT ON COLUMN EADM_ROLE.ROLENAME IS '角色名称';
COMMENT ON COLUMN EADM_ROLE.ROLEPERMISSION IS '角色权限';
COMMENT ON COLUMN EADM_ROLE.ROLESTATUS IS '角色状态(0启用1禁用)';
COMMENT ON COLUMN EADM_ROLE.CREATEDUSER IS '创建人';
COMMENT ON COLUMN EADM_ROLE.CREATEDAT IS '创建时间';
COMMENT ON COLUMN EADM_ROLE.UPDATEDUSER IS '更新人';
COMMENT ON COLUMN EADM_ROLE.UPDATEDAT IS '更新时间';
COMMENT ON COLUMN EADM_ROLE.DELETEDUSER IS '删除人';
COMMENT ON COLUMN EADM_ROLE.DELETEDAT IS '删除时间';
COMMENT ON COLUMN EADM_ROLE.DELETED IS '是否删除(0否1是)';
COMMENT ON TABLE EADM_ROLE IS '基础信息_角色信息表';

-- 更新时间
CREATE OR REPLACE TRIGGER TR_EADM_ROLE_UPDATEAT
BEFORE UPDATE ON EADM_ROLE
FOR EACH ROW
BEGIN
    :NEW.UPDATEDAT := SYSTIMESTAMP;
END;

--自定义主键
CREATE OR REPLACE TRIGGER TR_EADM_ROLE_ID
BEFORE INSERT ON EADM_ROLE
FOR EACH ROW
BEGIN
    :NEW.ID := 'ER' || LPAD(SEQ_ER.NEXTVAL, 10, '0');
END;

-- 写入数据
TRUNCATE TABLE EADM_ROLE;

INSERT INTO EADM_ROLE(ROLENAME, ROLEPERMISSION, CREATEDUSER)
VALUES('超级管理员', '{}', 'WANGCW');

INSERT INTO EADM_ROLE(ROLENAME, ROLEPERMISSION, CREATEDUSER)
VALUES('注册租户', '{}', 'WANGCW');

INSERT INTO EADM_ROLE(ROLENAME, ROLEPERMISSION, CREATEDUSER)
VALUES('分配租户', '{}', 'WANGCW');

-- 角色视图
CREATE OR REPLACE VIEW VI_ROLE
AS
SELECT ID, ROLENAME, ROLEPERMISSION, CASE ROLESTATUS WHEN 1 THEN '禁用' WHEN 0 THEN '启用' END AS ROLESTATUS, CREATEDAT
FROM EADM_ROLE
  WHERE DELETED = 0;

-- SELECT * FROM EADM_ROLE;
-- SELECT * FROM VI_ROLE;

-- 用户角色对应关系
CREATE TABLE EADM_USERROLE (
  ID INT GENERATED ALWAYS AS IDENTITY,
  USERID CHAR(12) NOT NULL,
  ROLEID CHAR(12) NOT NULL,
  CREATEDUSER VARCHAR2(50),
  CREATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  UPDATEDUSER VARCHAR2(50),
  UPDATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  DELETEDUSER VARCHAR2(50),
  DELETEDAT TIMESTAMP WITH LOCAL TIME ZONE,
  DELETED INTEGER DEFAULT 0
);

ALTER TABLE EADM_USERROLE ADD CONSTRAINT PK_USERROLE_ID PRIMARY KEY (ID);

ALTER TABLE EADM_USERROLE ADD CONSTRAINT FK_USERROLE_USERID_USER_ID FOREIGN KEY (USERID)
    REFERENCES EADM_USER (ID);
ALTER TABLE EADM_USERROLE ADD CONSTRAINT FK_ROLEID_ROLE_ID FOREIGN KEY (ROLEID)
    REFERENCES EADM_ROLE (ID);

COMMENT ON COLUMN EADM_USERROLE.ID IS '自增主键';
COMMENT ON COLUMN EADM_USERROLE.USERID IS '用户ID(EADM_USER.ID)';
COMMENT ON COLUMN EADM_USERROLE.ROLEID IS '角色ID(EADM_ROLE.ID)';
COMMENT ON COLUMN EADM_USERROLE.CREATEDUSER IS '创建人';
COMMENT ON COLUMN EADM_USERROLE.CREATEDAT IS '创建时间';
COMMENT ON COLUMN EADM_USERROLE.UPDATEDUSER IS '更新人';
COMMENT ON COLUMN EADM_USERROLE.UPDATEDAT IS '更新时间';
COMMENT ON COLUMN EADM_USERROLE.DELETEDUSER IS '删除人';
COMMENT ON COLUMN EADM_USERROLE.DELETEDAT IS '删除时间';
COMMENT ON COLUMN EADM_USERROLE.DELETED IS '是否删除(0否1是)';
COMMENT ON TABLE EADM_USERROLE IS '基础信息_用户角色对应关系表';

-- 更新时间
CREATE OR REPLACE TRIGGER TR_EADM_USERROLE_UPDATEAT
BEFORE UPDATE ON EADM_USERROLE
FOR EACH ROW
BEGIN
    :NEW.UPDATEDAT := SYSTIMESTAMP;
END;

-- 写入数据
-- SELECT * FROM EADM_USER;
-- SELECT * FROM EADM_ROLE;

INSERT INTO EADM_USERROLE(USERID, ROLEID, CREATEDUSER)
VALUES('EU0000000001', 'ER0000000001', 'WANGCW');

-- 用户角色信息视图
CREATE OR REPLACE VIEW VI_USERROLE
AS
SELECT B.ID, A.ID AS USERID, C.ID AS ROLEID, C.ROLENAME, B.UPDATEDAT
FROM EADM_USER A
INNER JOIN EADM_USERROLE B
  ON B.USERID=A.ID
  AND B.DELETED = 0
INNER JOIN EADM_ROLE C
  ON C.ID=B.ROLEID
  AND C.ROLESTATUS=0
  AND C.DELETED = 0
WHERE A.DELETED = 0;

-- 用户权限信息视图
CREATE OR REPLACE VIEW VI_USERPERMISSION
AS
SELECT B.ID, A.LOGINNAME, C.ROLEPERMISSION
FROM EADM_USER A
INNER JOIN EADM_USERROLE B
  ON B.USERID=A.ID
  AND B.DELETED = 0
INNER JOIN EADM_ROLE C
  ON C.ID=B.ROLEID
  AND C.ROLESTATUS = 0
  AND C.DELETED = 0
WHERE A.DELETED = 0;

-- SELECT * FROM VI_USERROLE;
-- SELECT * FROM VI_USERPERMISSION;

-- 定时任务信息
-- 创建序列
CREATE SEQUENCE SEQ_CR
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE TABLE EADM_CRONTAB (
  ID CHAR(12) NOT NULL,
  CRONNAME VARCHAR2(50) NOT NULL,
  CRONEXP VARCHAR2(50),
  CRONMFA VARCHAR2(50),
  STARTTIME TIMESTAMP WITH LOCAL TIME ZONE,
  ENDTIME TIMESTAMP WITH LOCAL TIME ZONE,
  CRONSTATUS SMALLINT DEFAULT 0,
  CREATEDUSER VARCHAR2(50),
  CREATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  UPDATEDUSER VARCHAR2(50),
  UPDATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  DELETEDUSER VARCHAR2(50),
  DELETEDAT TIMESTAMP WITH LOCAL TIME ZONE,
  DELETED INTEGER DEFAULT 0
);

ALTER TABLE EADM_CRONTAB ADD CONSTRAINT PK_CRONTAB_ID PRIMARY KEY (ID);
CREATE INDEX NON_CRONTAB_CRONNAME ON EADM_CRONTAB (CRONNAME ASC);

COMMENT ON COLUMN EADM_CRONTAB.ID IS '自定义主键(CR)';
COMMENT ON COLUMN EADM_CRONTAB.CRONNAME IS '任务名称';
COMMENT ON COLUMN EADM_CRONTAB.CRONEXP IS '定时表达式';
COMMENT ON COLUMN EADM_CRONTAB.CRONMFA IS '任务备注';
COMMENT ON COLUMN EADM_CRONTAB.STARTTIME IS '任务开始时间';
COMMENT ON COLUMN EADM_CRONTAB.ENDTIME IS '任务结束时间';
COMMENT ON COLUMN EADM_CRONTAB.CRONSTATUS IS '任务状态(0启用1禁用)';
COMMENT ON COLUMN EADM_CRONTAB.CREATEDUSER IS '创建人';
COMMENT ON COLUMN EADM_CRONTAB.CREATEDAT IS '创建时间';
COMMENT ON COLUMN EADM_CRONTAB.UPDATEDUSER IS '更新人';
COMMENT ON COLUMN EADM_CRONTAB.UPDATEDAT IS '更新时间';
COMMENT ON COLUMN EADM_CRONTAB.DELETEDUSER IS '删除人';
COMMENT ON COLUMN EADM_CRONTAB.DELETEDAT IS '删除时间';
COMMENT ON COLUMN EADM_CRONTAB.DELETED IS '是否删除(0否1是)';
COMMENT ON TABLE EADM_CRONTAB IS '基础信息_定时任务信息表';

-- 更新时间
CREATE OR REPLACE TRIGGER TR_EADM_CRONTAB_UPDATEAT
BEFORE UPDATE ON EADM_CRONTAB
FOR EACH ROW
BEGIN
    :NEW.UPDATEDAT := SYSTIMESTAMP;
END;

--自定义主键
CREATE OR REPLACE TRIGGER TR_EADM_CRONTAB_ID
BEFORE INSERT ON EADM_CRONTAB
FOR EACH ROW
BEGIN
    :NEW.ID := 'CR' || LPAD(SEQ_CR.NEXTVAL, 10, '0');
END;

-- 首页报表
CREATE TABLE EADM_DASHBOARD(
    ID INT GENERATED ALWAYS AS IDENTITY,
    DATATYPE SMALLINT NOT NULL,
    DATETYPE SMALLINT NOT NULL,
    LOGINNAME VARCHAR2(50) NOT NULL,
    DATAVALUE VARCHAR2(500),
    DATAJSON CLOB,
    CHECKDATE VARCHAR2(20) NOT NULL,
    UPDATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
    INSTERTIME TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP
);

ALTER TABLE EADM_DASHBOARD ADD CONSTRAINT PK_DASHBOARD_ID PRIMARY KEY (ID);

ALTER TABLE EADM_DASHBOARD ADD CONSTRAINT UNI_DASHBOARD_DDLC
    UNIQUE (DATATYPE, DATETYPE, LOGINNAME, CHECKDATE);

CREATE INDEX NON_DASHBOARD_DATATYPE ON EADM_DASHBOARD (DATATYPE ASC);
CREATE INDEX NON_DASHBOARD_DATETYPE ON EADM_DASHBOARD (DATETYPE ASC);
CREATE INDEX NON_DASHBOARD_LOGINNAME ON EADM_DASHBOARD (LOGINNAME ASC);
CREATE INDEX NON_DASHBOARD_CHECKDATE ON EADM_DASHBOARD (CHECKDATE ASC);

COMMENT ON COLUMN EADM_DASHBOARD.ID IS '自增主键';
COMMENT ON COLUMN EADM_DASHBOARD.DATATYPE IS '数据类型(1心率2步数3睡眠4里程5每月里程6每月收入7每月支出)';
COMMENT ON COLUMN EADM_DASHBOARD.DATETYPE IS '统计周期类型(1日2周3月4年)';
COMMENT ON COLUMN EADM_DASHBOARD.LOGINNAME IS '登录名';
COMMENT ON COLUMN EADM_DASHBOARD.DATAVALUE IS '数据值';
COMMENT ON COLUMN EADM_DASHBOARD.DATAJSON IS '数据JSON';
COMMENT ON COLUMN EADM_DASHBOARD.CHECKDATE IS '数据日期';
COMMENT ON COLUMN EADM_DASHBOARD.UPDATEDAT IS '更新时间';
COMMENT ON COLUMN EADM_DASHBOARD.INSTERTIME IS '插入时间';
COMMENT ON TABLE EADM_DASHBOARD IS '首页_看板报表';

-- 更新时间
CREATE OR REPLACE TRIGGER TR_EADM_DASHBOARD_UPDATEAT
BEFORE UPDATE ON EADM_DASHBOARD
FOR EACH ROW
BEGIN
    :NEW.UPDATEDAT := SYSTIMESTAMP;
END;

-- 过程运行日志
CREATE TABLE SYS_PROCLOG (
  ID INT GENERATED ALWAYS AS IDENTITY,
  PROCNAME VARCHAR2(50),
  TIMESPAN INT,
  RESULT INTEGER DEFAULT 1,
  ERRCODE VARCHAR2(5),
  ERRMESSAGE VARCHAR2(5000),
  INSERTTIME TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP
);

ALTER TABLE SYS_PROCLOG ADD CONSTRAINT PK_PROCLOG_ID PRIMARY KEY (ID);

CREATE INDEX NON_PROCLOG_PROCNAME ON SYS_PROCLOG (PROCNAME ASC);
CREATE INDEX NON_PROCLOG_INSERTTIME ON SYS_PROCLOG (INSERTTIME ASC);

COMMENT ON COLUMN SYS_PROCLOG.ID IS '自增主键';
COMMENT ON COLUMN SYS_PROCLOG.PROCNAME IS '过程名';
COMMENT ON COLUMN SYS_PROCLOG.TIMESPAN IS '耗时时长(秒)';
COMMENT ON COLUMN SYS_PROCLOG.RESULT IS '是否成功(0否1是)';
COMMENT ON COLUMN SYS_PROCLOG.ERRCODE IS '错误代码';
COMMENT ON COLUMN SYS_PROCLOG.ERRMESSAGE IS '错误详细信息';
COMMENT ON COLUMN SYS_PROCLOG.INSERTTIME IS '日志记录时间';
COMMENT ON TABLE SYS_PROCLOG IS '系统域_过程执行日志';

-- 设备信息
CREATE TABLE EADM_DEVICE (
  DEVICENO VARCHAR2(50) NOT NULL,
  IMEI VARCHAR2(50),
  SIMNO VARCHAR2(50),
  ENABLE INTEGER DEFAULT 1,
  REMARK VARCHAR2(200),
  CREATEDUSER VARCHAR2(50),
  CREATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  UPDATEDUSER VARCHAR2(50),
  UPDATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  DELETEDUSER VARCHAR2(50),
  DELETEDAT TIMESTAMP WITH LOCAL TIME ZONE,
  DELETED INTEGER DEFAULT 0
);

ALTER TABLE EADM_DEVICE ADD CONSTRAINT PK_DEVICE_DEVICENO PRIMARY KEY (DEVICENO);

CREATE INDEX NON_DEVICE_SIMNO ON EADM_DEVICE (SIMNO ASC);

COMMENT ON COLUMN EADM_DEVICE.DEVICENO IS '设备号(主键)';
COMMENT ON COLUMN EADM_DEVICE.IMEI IS '设备IMEI';
COMMENT ON COLUMN EADM_DEVICE.SIMNO IS 'SIM卡号';
COMMENT ON COLUMN EADM_DEVICE.ENABLE IS '设备状态(1启用0禁用)';
COMMENT ON COLUMN EADM_DEVICE.REMARK IS '设备描述';
COMMENT ON COLUMN EADM_DEVICE.CREATEDUSER IS '创建人';
COMMENT ON COLUMN EADM_DEVICE.CREATEDAT IS '创建时间';
COMMENT ON COLUMN EADM_DEVICE.UPDATEDUSER IS '更新人';
COMMENT ON COLUMN EADM_DEVICE.UPDATEDAT IS '更新时间';
COMMENT ON COLUMN EADM_DEVICE.DELETEDUSER IS '删除人';
COMMENT ON COLUMN EADM_DEVICE.DELETEDAT IS '删除时间';
COMMENT ON COLUMN EADM_DEVICE.DELETED IS '是否删除(0否1是)';
COMMENT ON TABLE EADM_DEVICE IS '业务域_设备信息';

-- 更新时间
CREATE OR REPLACE TRIGGER TR_EADM_DEVICE_UPDATEAT
BEFORE UPDATE ON EADM_DEVICE
FOR EACH ROW
BEGIN
    :NEW.UPDATEDAT := SYSTIMESTAMP;
END;

-- 写入数据
TRUNCATE TABLE EADM_DEVICE;
INSERT INTO EADM_DEVICE (DEVICENO, REMARK, CREATEDUSER)
VALUES ('16053489111', '充电宝', 'WANGCW');
INSERT INTO EADM_DEVICE (DEVICENO, REMARK, CREATEDUSER)
VALUES ('868977061978771', '手表', 'WANGCW');
-- 注意！ORACLE不支持 一个 VALUES后跟多个插入值

-- SELECT * FROM EADM_DEVICE;

-- 人员设备对应关系
CREATE TABLE EADM_USERDEVICE (
  ID INT GENERATED ALWAYS AS IDENTITY,
  USERID CHAR(12) NOT NULL,
  LOGINNAME VARCHAR2(50) NOT NULL,
  DEVICENO VARCHAR2(50) NOT NULL,
  CREATEDUSER VARCHAR2(50),
  CREATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  UPDATEDUSER VARCHAR2(50),
  UPDATEDAT TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  DELETEDUSER VARCHAR2(50),
  DELETEDAT TIMESTAMP WITH LOCAL TIME ZONE,
  DELETED INTEGER DEFAULT 0
);

ALTER TABLE EADM_USERDEVICE ADD CONSTRAINT PK_USERDEVICE_ID PRIMARY KEY (ID);

ALTER TABLE EADM_USERDEVICE ADD CONSTRAINT FK_USERDEVICE_USERID_USER_ID FOREIGN KEY (USERID)
    REFERENCES EADM_USER (ID);
ALTER TABLE EADM_USERDEVICE ADD CONSTRAINT FK_LOGINNAME_USER_LOGINNAME FOREIGN KEY (LOGINNAME)
    REFERENCES EADM_USER (LOGINNAME);
ALTER TABLE EADM_USERDEVICE ADD CONSTRAINT FK_DEVICENO_DEVICE_DEVICENO FOREIGN KEY (DEVICENO)
    REFERENCES EADM_DEVICE (DEVICENO);

COMMENT ON COLUMN EADM_USERDEVICE.ID IS '自增主键';
COMMENT ON COLUMN EADM_USERDEVICE.USERID IS '用户ID(EADM_USER.ID)';
COMMENT ON COLUMN EADM_USERDEVICE.LOGINNAME IS '用户登录名(EADM_USER.LOGINNAME)';
COMMENT ON COLUMN EADM_USERDEVICE.DEVICENO IS '设备ID(EADM_DEVICE.DEVICENO)';
COMMENT ON COLUMN EADM_USERDEVICE.CREATEDUSER IS '创建人';
COMMENT ON COLUMN EADM_USERDEVICE.CREATEDAT IS '创建时间';
COMMENT ON COLUMN EADM_USERDEVICE.UPDATEDUSER IS '更新人';
COMMENT ON COLUMN EADM_USERDEVICE.UPDATEDAT IS '更新时间';
COMMENT ON COLUMN EADM_USERDEVICE.DELETEDUSER IS '删除人';
COMMENT ON COLUMN EADM_USERDEVICE.DELETEDAT IS '删除时间';
COMMENT ON COLUMN EADM_USERDEVICE.DELETED IS '是否删除(0否1是)';
COMMENT ON TABLE EADM_USERDEVICE IS '业务域_人员设备对应关系';

-- 更新时间
CREATE OR REPLACE TRIGGER TR_EADM_USERDEVICE_UPDATEAT
BEFORE UPDATE ON EADM_USERDEVICE
FOR EACH ROW
BEGIN
    :NEW.UPDATEDAT := SYSTIMESTAMP;
END;

-- 写入数据
INSERT INTO EADM_USERDEVICE(USERID, LOGINNAME, DEVICENO, CREATEDUSER)
SELECT 'EU0000000001', 'WANGCW', DEVICENO, 'WANGCW'
FROM EADM_DEVICE;

-- SELECT * FROM EADM_USERDEVICE;

-- 业务数据_车辆定位信息
CREATE TABLE LC_CARLOCDAILY (
  PTIME TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
  DEVICENO VARCHAR2(20),
  LAT NUMERIC(9,6),
  LNG NUMERIC(9,6),
  DIRCT INT,
  SPEED INT,
  MILEAGE NUMERIC(18,2),
  HIGHT INT,
  GNSSNUM INT,
  RSSI INT,
  RECEIVETIME TIMESTAMP WITH LOCAL TIME ZONE,
  INSERTTIME TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP
);

ALTER TABLE LC_CARLOCDAILY ADD CONSTRAINT PK_CARLOCDAILY_PTIME PRIMARY KEY (PTIME);

CREATE INDEX NON_CARLOCDAILY_DEVICENO ON LC_CARLOCDAILY (DEVICENO ASC);

COMMENT ON COLUMN LC_CARLOCDAILY.PTIME IS '设备上传时间(主键)';
COMMENT ON COLUMN LC_CARLOCDAILY.DEVICENO IS '设备编码(ICCID)';
COMMENT ON COLUMN LC_CARLOCDAILY.LAT IS '经度';
COMMENT ON COLUMN LC_CARLOCDAILY.LNG IS '纬度';
COMMENT ON COLUMN LC_CARLOCDAILY.DIRCT IS '方向角';
COMMENT ON COLUMN LC_CARLOCDAILY.SPEED IS '速度';
COMMENT ON COLUMN LC_CARLOCDAILY.MILEAGE IS '里程';
COMMENT ON COLUMN LC_CARLOCDAILY.HIGHT IS '海拔';
COMMENT ON COLUMN LC_CARLOCDAILY.GNSSNUM IS 'GPS卫星数量';
COMMENT ON COLUMN LC_CARLOCDAILY.RSSI IS '4G信号值';
COMMENT ON COLUMN LC_CARLOCDAILY.RECEIVETIME IS 'GATEWAY处理时间';
COMMENT ON COLUMN LC_CARLOCDAILY.INSERTTIME IS '数据写入时间';
COMMENT ON TABLE LC_CARLOCDAILY IS '车辆日常定位信息';

-- 业务数据_手表信息
CREATE TABLE LC_WATCHDAILY (
  PTIME TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
  STEPS VARCHAR2(50),
  HEARTBEAT VARCHAR2(50),
  ROLL VARCHAR2(50),
  BODYTEMPERATURE VARCHAR2(50),
  WRISTTEMPERATURE VARCHAR2(50),
  BLOODSUGAR VARCHAR2(50),
  DIASTOLIC VARCHAR2(50),
  SHRINK VARCHAR2(50),
  BLOODOXYGEN VARCHAR2(50),
  SLEEPTYPE VARCHAR2(50),
  SLEEPSTARTTIME VARCHAR2(50),
  SLEEPENDTIME VARCHAR2(50),
  SLEEPMINUTE VARCHAR2(50),
  SIGNAL VARCHAR2(50),
  BATTERY VARCHAR2(50),
  LAT VARCHAR2(50),
  LNG VARCHAR2(50),
  SPEED VARCHAR2(50),
  INSERTTIME TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP
);

ALTER TABLE LC_WATCHDAILY ADD CONSTRAINT PK_WATCHDAILY_PTIME PRIMARY KEY (PTIME);

COMMENT ON COLUMN LC_WATCHDAILY.PTIME IS '数据获取时间';
COMMENT ON COLUMN LC_WATCHDAILY.STEPS IS '步数';
COMMENT ON COLUMN LC_WATCHDAILY.HEARTBEAT IS '心率';
COMMENT ON COLUMN LC_WATCHDAILY.ROLL IS '翻转数';
COMMENT ON COLUMN LC_WATCHDAILY.BODYTEMPERATURE IS '体温';
COMMENT ON COLUMN LC_WATCHDAILY.WRISTTEMPERATURE IS '腕温';
COMMENT ON COLUMN LC_WATCHDAILY.BLOODSUGAR IS '血糖';
COMMENT ON COLUMN LC_WATCHDAILY.DIASTOLIC IS '舒张压';
COMMENT ON COLUMN LC_WATCHDAILY.SHRINK IS '收缩压';
COMMENT ON COLUMN LC_WATCHDAILY.BLOODOXYGEN IS '血氧';
COMMENT ON COLUMN LC_WATCHDAILY.SLEEPTYPE IS '睡眠类型(1深度睡眠2浅度睡眠3醒来时长)';
COMMENT ON COLUMN LC_WATCHDAILY.SLEEPSTARTTIME IS '睡眠开始时间';
COMMENT ON COLUMN LC_WATCHDAILY.SLEEPENDTIME IS '睡眠结束时间';
COMMENT ON COLUMN LC_WATCHDAILY.SLEEPMINUTE IS '睡眠时长(分钟)';
COMMENT ON COLUMN LC_WATCHDAILY.SIGNAL IS '信号值';
COMMENT ON COLUMN LC_WATCHDAILY.BATTERY IS '电池电量';
COMMENT ON COLUMN LC_WATCHDAILY.LAT IS '定位纬度(GPS)';
COMMENT ON COLUMN LC_WATCHDAILY.LNG IS '定位经度(GPS)';
COMMENT ON COLUMN LC_WATCHDAILY.SPEED IS '速度';
COMMENT ON COLUMN LC_WATCHDAILY.INSERTTIME IS '数据写入时间';
COMMENT ON TABLE LC_WATCHDAILY IS '手表日常数据';

-- 手表预警
CREATE TABLE LC_WATCHALARM (
  ID INT GENERATED ALWAYS AS IDENTITY,
  ALERTTYPE VARCHAR2(10),
  ALERTINFO VARCHAR2(1000),
  HEARTNUM VARCHAR2(50),
  LASTTEMPER VARCHAR2(50),
  INSERTTIME TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP
);

ALTER TABLE LC_WATCHALARM ADD CONSTRAINT PK_WATCHALARM_ID PRIMARY KEY (ID);

CREATE INDEX NON_WATCHALARM_ALERTTYPE ON LC_WATCHALARM (ALERTTYPE ASC);

COMMENT ON COLUMN LC_WATCHALARM.ID IS '自增主键';
COMMENT ON COLUMN LC_WATCHALARM.ALERTTYPE IS '预警类型';
COMMENT ON COLUMN LC_WATCHALARM.ALERTINFO IS '报警信息内容';
COMMENT ON COLUMN LC_WATCHALARM.HEARTNUM IS '当前心率';
COMMENT ON COLUMN LC_WATCHALARM.LASTTEMPER IS '当前体温';
COMMENT ON TABLE LC_WATCHALARM IS '手表日常报警信息';

-- 财务数据
CREATE TABLE FN_PAYBILLDETAIL (
  ID INT GENERATED ALWAYS AS IDENTITY,
  OWNER VARCHAR2(50),
  SOURCETYPE INT,
  INOROUT VARCHAR2(10),
  COUNTERPARTY VARCHAR2(100),
  COUNTERBANK VARCHAR2(100),
  COUNTERACCOUNT VARCHAR2(50),
  GOODSCOMMENT VARCHAR2(200),
  PAYMETHOD VARCHAR2(50),
  AMOUNT NUMERIC(18,2),
  BALANCE NUMERIC(18,2),
  CURRENCY VARCHAR2(50),
  PAYSTATUS VARCHAR2(50),
  TRADETYPE VARCHAR2(50),
  TRADEORDERNO VARCHAR2(100),
  COUNTERORDERNO VARCHAR2(100),
  TRADETIME TIMESTAMP WITH LOCAL TIME ZONE,
  BILLCOMMENT VARCHAR2(500),
  INSERTTIME TIMESTAMP WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP,
  DELETEDUSER VARCHAR2(50),
  DELETEDAT TIMESTAMP WITH LOCAL TIME ZONE,
  DELETED INTEGER DEFAULT 0
);

ALTER TABLE FN_PAYBILLDETAIL ADD CONSTRAINT PK_PAYBILLDETAIL_ID PRIMARY KEY (ID);

CREATE INDEX NON_PAYBILLDETAIL_SOURCE ON FN_PAYBILLDETAIL (SOURCETYPE ASC);
CREATE INDEX NON_PAYBILLDETAIL_INOROUT ON FN_PAYBILLDETAIL (INOROUT ASC);
CREATE INDEX NON_PAYBILLDETAIL_PAYMETHOD ON FN_PAYBILLDETAIL (PAYMETHOD ASC);
CREATE INDEX NON_PAYBILLDETAIL_PAYSTATUS ON FN_PAYBILLDETAIL (PAYSTATUS ASC);
CREATE INDEX NON_PAYBILLDETAIL_TRADETYPE ON FN_PAYBILLDETAIL (TRADETYPE ASC);
CREATE INDEX NON_PAYBILLDETAIL_TRADETIME ON FN_PAYBILLDETAIL (TRADETIME ASC);

COMMENT ON COLUMN FN_PAYBILLDETAIL.ID IS '自增主键';
COMMENT ON COLUMN FN_PAYBILLDETAIL.OWNER IS '来源人(姓名)';
COMMENT ON COLUMN FN_PAYBILLDETAIL.SOURCETYPE IS '来源:1支付宝2微信3青岛银行4中国银行';
COMMENT ON COLUMN FN_PAYBILLDETAIL.INOROUT IS '收/支';
COMMENT ON COLUMN FN_PAYBILLDETAIL.COUNTERPARTY IS '交易对方';
COMMENT ON COLUMN FN_PAYBILLDETAIL.COUNTERBANK IS '对方开户行';
COMMENT ON COLUMN FN_PAYBILLDETAIL.COUNTERACCOUNT IS '对方账号';
COMMENT ON COLUMN FN_PAYBILLDETAIL.GOODSCOMMENT IS '商品说明';
COMMENT ON COLUMN FN_PAYBILLDETAIL.PAYMETHOD IS '收/付款方式';
COMMENT ON COLUMN FN_PAYBILLDETAIL.AMOUNT IS '金额';
COMMENT ON COLUMN FN_PAYBILLDETAIL.BALANCE IS '余额';
COMMENT ON COLUMN FN_PAYBILLDETAIL.CURRENCY IS '币种';
COMMENT ON COLUMN FN_PAYBILLDETAIL.PAYSTATUS IS '交易状态';
COMMENT ON COLUMN FN_PAYBILLDETAIL.TRADETYPE IS '交易分类';
COMMENT ON COLUMN FN_PAYBILLDETAIL.TRADEORDERNO IS '交易订单号';
COMMENT ON COLUMN FN_PAYBILLDETAIL.COUNTERORDERNO IS '商家订单号';
COMMENT ON COLUMN FN_PAYBILLDETAIL.TRADETIME IS '交易时间';
COMMENT ON COLUMN FN_PAYBILLDETAIL.BILLCOMMENT IS '交易备注';
COMMENT ON COLUMN FN_PAYBILLDETAIL.INSERTTIME IS '数据写入时间';
COMMENT ON COLUMN FN_PAYBILLDETAIL.DELETEDUSER IS '删除人账号';
COMMENT ON COLUMN FN_PAYBILLDETAIL.DELETEDAT IS '删除时间';
COMMENT ON COLUMN FN_PAYBILLDETAIL.DELETED IS '是否删除(0否1是)';
COMMENT ON TABLE FN_PAYBILLDETAIL IS '账单明细';
