name: ex_doc_publish

on:
  push:
    tags:
      - 'doc*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27.2.3'
          rebar3-version: '3.24.0'
          
      - name: Generate Documentation
        run: |
          rebar3 ex_doc
          echo "docs.wongcw.cn" > doc/CNAME
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'doc'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
