name: release

on:
  push:
    tags:
        - 'v*'

env:
  OTP-VERSION: 26.2.2
  REBAR3-VERSION: 3.22.1

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: erlef/setup-beam@v1.17.5
        with:
          otp-version: ${{ env.OTP-VERSION }}
          rebar3-version: ${{ env.REBAR3-VERSION }}

      - uses: actions/cache@v4.0.2
        id: rebar3-cache
        with:
          path: |
            ~/.cache/rebar3
            _build
          key: ${{ runner.os }}-${{ env.OTP-VERSION }}-${{ env.REBAR3-VERSION }}-${{ hashFiles('rebar.lock') }}

      - name: compile
        run: |
          rebar3 clean
          rebar3 as prod release
          tar -czvf eadm-${{ github.ref_name }}.tar.gz _build/prod/rel/eadm

      - name: release create
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        with:
          tag_name: main
          release_name: Release-main
          draft: false
          prerelease: false

      - name: release upload
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./eadm-${{ github.ref_name }}.tar.gz
          asset_name: eadm-${{ github.ref_name }}.tar.gz
          asset_content_type: application/octet-stream
